# Generated by Django 4.1.3 on 2022-12-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default='Dec. 01, 1900, 10:15 p.m.'),
        ),
    ]
