# Generated by Django 4.1.3 on 2022-12-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_subject_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
    ]
