# Generated by Django 4.1.3 on 2022-12-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
