# Generated by Django 4.1.3 on 2022-12-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_attendance_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
